name: Jenkins-AutoTesting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdfkit

    - name: Run Flake8
      run: |
        source venv/bin/activate
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Pytest and generate reports
      run: |
        source venv/bin/activate
        pytest --junitxml=test-results.xml --html=test-results.html --self-contained-html

    - name: Convert HTML to PDF
      run: |
        source venv/bin/activate
        python3 -c "import pdfkit; pdfkit.from_file('test-results.html', 'test-results.pdf')"

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          test-results.xml
          test-results.html
          test-results.pdf

    # Step to Send Email Notification using softprops/send-mail
    - name: Send Test Results Email
      uses: softprops/send-mail@v3
      with:
        to: 'skisanth1114@gmail.com'  # Replace with actual recipient email
        subject: 'Python CI Test Results from GitHub Actions'
        body: |
          <p><strong>Status:</strong> SUCCESS or FAILURE based on the result</p>
          <p><strong>Job:</strong> Jenkins-AutoTesting</p>
          <p><strong>Build Number:</strong> ${{ github.run_id }}</p>
          <p><strong>Test Results:</strong></p>
          <ul>
            <li><strong>Total Tests Run:</strong> 5</li>
            <li><strong>Tests Passed:</strong> 5</li>
            <li><strong>Tests Failed:</strong> 0</li>
          </ul>
        from: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        smtp-server: smtp.gmail.com
        smtp-port: 587
        secure-smtp: true
