name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pdfkit

      - name: Run flake8 Code Quality Check
        run: |
          source venv/bin/activate
          flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests and Generate Reports
        run: |
          source venv/bin/activate
          pytest --junitxml=test-results.xml --html=test-results.html --self-contained-html

      - name: Convert HTML to PDF
        run: |
          source venv/bin/activate
          python3 -c "
import pdfkit
pdfkit.from_file('test-results.html', 'test-results.pdf')
"

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: |
            test-results.xml
            test-results.html
            test-results.pdf

      - name: Notify on Success
        if: success()
        run: |
          echo "✅ Tests passed for ${{ github.repository }}!"
          echo "Sending success email to skisanth1114@gmail.com (this is a placeholder)."

      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Tests failed for ${{ github.repository }}!"
          echo "Sending failure email to skisanth1114@gmail.com (this is a placeholder)."
