name: Python CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdfkit yagmail

    - name: Run Flake8
      run: |
        source venv/bin/activate
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Run Pytest and generate reports
      run: |
        source venv/bin/activate
        pytest --junitxml=test-results.xml --html=test-results.html --self-contained-html

    - name: Convert HTML to PDF
      run: |
        source venv/bin/activate
        python3 -c "import pdfkit; pdfkit.from_file('test-results.html', 'test-results.pdf')"

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: |
          test-results.xml
          test-results.html
          test-results.pdf

    - name: Send email with reports
      if: always()
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        source venv/bin/activate || true
        python3 -c "
import os
import yagmail
attachments = []
for f in ['test-results.html', 'test-results.pdf']:
    if os.path.exists(f):
        attachments.append(f)
yag = yagmail.SMTP(user='skisanth1114@gmail.com', password=os.environ['EMAIL_PASSWORD'])
yag.send(
    to='skisanth1114@gmail.com',
    subject='🔔 GitHub Actions CI Pipeline Notification',
    contents='Build finished. Reports (if available) are attached.',
    attachments=attachments
)
"
